
<?php
defined('BASEPATH') OR exit('No direct script access allowed');
?>
<form action='<?=base_url()?>crearevento' method='post'>
<div>Equipo1:&nbsp;<input type='text' name='equipo1' required>&nbsp;&nbsp;
Goles:&nbsp;<input type='number' name='marcador1' value='0' required></div>
<div>Equipo2:&nbsp;<input type='text' name='equipo2' required>&nbsp;&nbsp;
Goles:&nbsp;<input type='number' name='marcador2' value='0' required></div>
<div><input type='submit' value='Crear'></div>
</form>


   