<form class="form-signin" action="<?=base_url()?>login" method="post">
        <h2 class="form-signin-heading">SARA</h2>
        
        <?php if($errors!=''):?>
                  <div class="alert alert-danger" role="alert"><?=$this->session->flashdata('errors')?></div>
        <?php endif;?>
        <label for="inputUsername" class="sr-only">Username</label>
        <input type="text" name="user" id="inputUsername" class="form-control" placeholder="Username" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Ingresar</button>
      </form>